### PR TITLE
Remove change value

### PR DESCRIPTION
**Pull request by grod220**
Closes https://github.com/penumbra-zone/dex-explorer/issues/152

Before:
Screenshot 2024-11-25 at 1 08 11 PM

After:
Screenshot 2024-11-25 at 1 08 05 PM

### CODE REVIEW

**Review by VanishMax — COMMENTED** [review]
question: what is the reason of removing the change value? It was really useful for me personally, it is almost the first thing I look for in similar websites

**Comment by grod220** [comment]
Amongst the feedback in the review from @hdevalence. I'm not sure a base change number denominated in the asset denom is that understandable by users.

**Comment by hdevalence** [comment]
Yeah, open to discussion on it but my opinion is/was that reporting an absolute number for the change is less informative than a percent and that it's visually cleaner to just show the relative number. But if others feel that it's useful we can leave it in

**Comment by hdevalence** [comment]
I have weak conviction on this point

**Comment by TalDerei** [comment]
I personally find it very useful to keep, as it's the first thing I look for as well. Dolemite only shows the percentage change, but I found myself spending more time trying to interpret the price information.

Screenshot 2024-11-25 at 6 58 19 AM

**Pull request closed without merging**
